version: "3.9"

services:
  # go-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: "go-app"
  #   command: air
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./:/app
  #   depends_on:
  #     - mongodb

  mongodb:
    image: "mongo:7.0.8"
    container_name: "mongo-db"
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    ports:
      - 27017:27017

  mongo-express:
    image: "mongo-express"
    container_name: "mongo-express-db"
    restart: on-failure
    ports:
      - 8082:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
